# Generated by Django 3.2.9 on 2023-05-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0002_auto_20230512_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
